name: ct-superres-mps
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pytorch::pytorch>=2.2.0
  - pytorch::torchvision
  - numpy>=1.24
  - scipy>=1.10
  - nibabel>=5.0
  - pydicom>=2.3
  - scikit-image>=0.20
  - tqdm>=4.65
  - pyyaml>=6.0
  - tensorboard>=2.12
  - matplotlib>=3.7
  - pandas>=2.0
  - pytest>=7.3
  - pip
  - pip:
    - lpips>=0.1.4
    - einops>=0.7.0
