#!/bin/bash
# Alternative download script using wget and TCIA manifest

OUTPUT_DIR="/Users/kuntalkokate/Desktop/LLM Agent - CT scan upres/data/unprocessed"

echo "======================================================================"
echo "LIDC-IDRI Alternative Download Methods"
echo "======================================================================"
echo ""
echo "The TCIA API has rate limits and may not work reliably for bulk downloads."
echo "Here are recommended alternatives:"
echo ""
echo "METHOD 1: NBIA Data Retriever (Recommended)"
echo "----------------------------------------------------------------------"
echo "1. Download NBIA Data Retriever for macOS:"
echo "   https://wiki.cancerimagingarchive.net/display/NBIA/Downloading+TCIA+Images"
echo ""
echo "2. Install and launch the application"
echo ""
echo "3. Search for 'LIDC-IDRI' collection"
echo ""
echo "4. Select patients to download (or select all)"
echo ""
echo "5. Set download location to:"
echo "   $OUTPUT_DIR"
echo ""
echo "6. Click 'Download'"
echo ""
echo ""
echo "METHOD 2: Direct Download via Browser/wget"
echo "----------------------------------------------------------------------"
echo "Download sample cases from TCIA directly:"
echo ""
echo "# Create output directory"
echo "mkdir -p \"$OUTPUT_DIR\""
echo ""
echo "# TCIA provides a downloadable manifest file"
echo "# Visit: https://www.cancerimagingarchive.net/collection/lidc-idri/"
echo "# Click 'Download' and use the NBIA Data Retriever"
echo ""
echo ""
echo "METHOD 3: Kaggle Dataset (Simplified)"
echo "----------------------------------------------------------------------"
echo "A preprocessed version is available on Kaggle:"
echo ""
echo "1. Visit: https://www.kaggle.com/datasets/justinkirby/the-cancer-imaging-archive-lidcidri"
echo "2. Download the dataset"
echo "3. Extract to: $OUTPUT_DIR"
echo ""
echo ""
echo "METHOD 4: Sample Data for Testing"
echo "----------------------------------------------------------------------"
echo "For quick testing, you can use synthetic data:"
echo ""
echo "python scripts/create_sample_data.py --output-dir ./data/unprocessed --num-samples 5"
echo ""
echo "======================================================================"
echo ""
echo "After downloading, run:"
echo "  python scripts/prepare_dataset.py \\"
echo "    --dicom-root $OUTPUT_DIR \\"
echo "    --output-dir ./data/processed"
echo ""